version: '3.7'

services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web1
      - web2
    networks:
      - load-balancer

  web1:
    image: simple-app
    container_name: web1
    environment:
      - "PORT=8001"
    # run uwsgi server
    command: uwsgi --http :8001 --wsgi-file /app.py --callable app --master --processes 4 --threads 2
    networks:
      - load-balancer

  web2:
    image: simple-app
    container_name: web2
    environment:
      - "PORT=8002"
    # run uwsgi server
    command: uwsgi --http :8002 --wsgi-file /app.py --callable app --master --processes 4 --threads 2
    networks:
      - load-balancer

networks:
  load-balancer:
    driver: bridge
